// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionInitializeResult {
  var success: Bool
  var statusKey: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionInitializeResult? {
    let success = pigeonVar_list[0] as! Bool
    let statusKey = pigeonVar_list[1] as! String

    return SessionInitializeResult(
      success: success,
      statusKey: statusKey
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      statusKey,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CounterRequest {
  var counter: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CounterRequest? {
    let counter = pigeonVar_list[0] as! Int64

    return CounterRequest(
      counter: counter
    )
  }
  func toList() -> [Any?] {
    return [
      counter
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CounterResult {
  var success: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CounterResult? {
    let success = pigeonVar_list[0] as! Bool

    return CounterResult(
      success: success
    )
  }
  func toList() -> [Any?] {
    return [
      success
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionStateEvent {
  var statusKey: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionStateEvent? {
    let statusKey = pigeonVar_list[0] as! String

    return SessionStateEvent(
      statusKey: statusKey
    )
  }
  func toList() -> [Any?] {
    return [
      statusKey
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CounterUpdateEvent {
  var counter: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CounterUpdateEvent? {
    let counter = pigeonVar_list[0] as! Int64

    return CounterUpdateEvent(
      counter: counter
    )
  }
  func toList() -> [Any?] {
    return [
      counter
    ]
  }
}

private class WatchCommunicationApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SessionInitializeResult.fromList(self.readValue() as! [Any?])
    case 130:
      return CounterRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return CounterResult.fromList(self.readValue() as! [Any?])
    case 132:
      return SessionStateEvent.fromList(self.readValue() as! [Any?])
    case 133:
      return CounterUpdateEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class WatchCommunicationApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SessionInitializeResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CounterRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CounterResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? SessionStateEvent {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CounterUpdateEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class WatchCommunicationApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return WatchCommunicationApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return WatchCommunicationApiPigeonCodecWriter(data: data)
  }
}

class WatchCommunicationApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = WatchCommunicationApiPigeonCodec(readerWriter: WatchCommunicationApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WatchCommunicationHostApi {
  func initializeSession(completion: @escaping (Result<SessionInitializeResult, Error>) -> Void)
  func sendCounter(request: CounterRequest, completion: @escaping (Result<CounterResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WatchCommunicationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { WatchCommunicationApiPigeonCodec.shared }
  /// Sets up an instance of `WatchCommunicationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WatchCommunicationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.WatchCommunicationHostApi.initializeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeSessionChannel.setMessageHandler { _, reply in
        api.initializeSession { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeSessionChannel.setMessageHandler(nil)
    }
    let sendCounterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.WatchCommunicationHostApi.sendCounter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendCounterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CounterRequest
        api.sendCounter(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendCounterChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WatchCommunicationFlutterApiProtocol {
  func onSessionStateChanged(event eventArg: SessionStateEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCounterUpdated(event eventArg: CounterUpdateEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WatchCommunicationFlutterApi: WatchCommunicationFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: WatchCommunicationApiPigeonCodec {
    return WatchCommunicationApiPigeonCodec.shared
  }
  func onSessionStateChanged(event eventArg: SessionStateEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onSessionStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onCounterUpdated(event eventArg: CounterUpdateEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onCounterUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
