// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// 画像メタデータ
class ImageMetadata {
  ImageMetadata({
    required this.id,
    required this.fileName,
    required this.fileSize,
    required this.width,
    required this.height,
    required this.timestamp,
  });

  String id;

  String fileName;

  int fileSize;

  int width;

  int height;

  double timestamp;

  Object encode() {
    return <Object?>[
      id,
      fileName,
      fileSize,
      width,
      height,
      timestamp,
    ];
  }

  static ImageMetadata decode(Object result) {
    result as List<Object?>;
    return ImageMetadata(
      id: result[0]! as String,
      fileName: result[1]! as String,
      fileSize: result[2]! as int,
      width: result[3]! as int,
      height: result[4]! as int,
      timestamp: result[5]! as double,
    );
  }
}

/// 転送進捗情報
class TransferProgress {
  TransferProgress({
    required this.imageId,
    required this.progress,
    required this.bytesTransferred,
    required this.totalBytes,
    required this.transferSpeed,
    required this.estimatedTimeRemaining,
  });

  String imageId;

  double progress;

  int bytesTransferred;

  int totalBytes;

  double transferSpeed;

  double estimatedTimeRemaining;

  Object encode() {
    return <Object?>[
      imageId,
      progress,
      bytesTransferred,
      totalBytes,
      transferSpeed,
      estimatedTimeRemaining,
    ];
  }

  static TransferProgress decode(Object result) {
    result as List<Object?>;
    return TransferProgress(
      imageId: result[0]! as String,
      progress: result[1]! as double,
      bytesTransferred: result[2]! as int,
      totalBytes: result[3]! as int,
      transferSpeed: result[4]! as double,
      estimatedTimeRemaining: result[5]! as double,
    );
  }
}

/// 転送履歴アイテム
class TransferHistoryItem {
  TransferHistoryItem({
    required this.metadata,
    required this.status,
    this.completedAt,
  });

  ImageMetadata metadata;

  int status;

  double? completedAt;

  Object encode() {
    return <Object?>[
      metadata,
      status,
      completedAt,
    ];
  }

  static TransferHistoryItem decode(Object result) {
    result as List<Object?>;
    return TransferHistoryItem(
      metadata: result[0]! as ImageMetadata,
      status: result[1]! as int,
      completedAt: result[2] as double?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ImageMetadata) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is TransferProgress) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is TransferHistoryItem) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return ImageMetadata.decode(readValue(buffer)!);
      case 130: 
        return TransferProgress.decode(readValue(buffer)!);
      case 131: 
        return TransferHistoryItem.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter → iOS への呼び出しインターフェース
class ImageTransferHostApi {
  /// Constructor for [ImageTransferHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ImageTransferHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 画像を転送
  /// imageData: JPEG形式のバイナリデータ
  Future<void> transferImage(Uint8List imageData, ImageMetadata metadata) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.transferImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[imageData, metadata]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 転送をキャンセル
  Future<void> cancelTransfer(String imageId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.cancelTransfer$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[imageId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 転送履歴を取得
  Future<List<TransferHistoryItem>> getTransferHistory() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.getTransferHistory$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<TransferHistoryItem>();
    }
  }

  /// 進行中の転送一覧を取得
  Future<List<TransferProgress>> getActiveTransfers() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.getActiveTransfers$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<TransferProgress>();
    }
  }
}

/// iOS → Flutter への通知インターフェース
abstract class ImageTransferFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// 進捗が更新された
  void onProgressUpdated(TransferProgress progress);

  /// 転送が完了した
  void onTransferCompleted(String imageId);

  /// 転送が失敗した
  void onTransferFailed(String imageId, String error);

  static void setUp(ImageTransferFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onProgressUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onProgressUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TransferProgress? arg_progress = (args[0] as TransferProgress?);
          assert(arg_progress != null,
              'Argument for dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onProgressUpdated was null, expected non-null TransferProgress.');
          try {
            api.onProgressUpdated(arg_progress!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferCompleted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferCompleted was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_imageId = (args[0] as String?);
          assert(arg_imageId != null,
              'Argument for dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferCompleted was null, expected non-null String.');
          try {
            api.onTransferCompleted(arg_imageId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferFailed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferFailed was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_imageId = (args[0] as String?);
          assert(arg_imageId != null,
              'Argument for dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferFailed was null, expected non-null String.');
          final String? arg_error = (args[1] as String?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferFailed was null, expected non-null String.');
          try {
            api.onTransferFailed(arg_imageId!, arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
