// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// メッセージデータを表すクラス
///
/// transferUserInfoで送受信されるデータ構造
class MessageData {
  MessageData({
    required this.id,
    required this.text,
    required this.sender,
    required this.timestamp,
    required this.isRead,
  });

  /// メッセージID（UUID）
  String id;

  /// メッセージ本文
  String text;

  /// 送信元（"iPhone" or "Watch"）
  String sender;

  /// 送信時刻（Unix timestamp）
  double timestamp;

  /// 既読フラグ
  bool isRead;

  Object encode() {
    return <Object?>[
      id,
      text,
      sender,
      timestamp,
      isRead,
    ];
  }

  static MessageData decode(Object result) {
    result as List<Object?>;
    return MessageData(
      id: result[0]! as String,
      text: result[1]! as String,
      sender: result[2]! as String,
      timestamp: result[3]! as double,
      isRead: result[4]! as bool,
    );
  }
}

/// キュー状態を表すクラス
class QueueStatus {
  QueueStatus({
    required this.outstandingCount,
    required this.isTransferring,
  });

  /// キューに残っている転送の数
  int outstandingCount;

  /// 現在転送中かどうか
  bool isTransferring;

  Object encode() {
    return <Object?>[
      outstandingCount,
      isTransferring,
    ];
  }

  static QueueStatus decode(Object result) {
    result as List<Object?>;
    return QueueStatus(
      outstandingCount: result[0]! as int,
      isTransferring: result[1]! as bool,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MessageData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is QueueStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return MessageData.decode(readValue(buffer)!);
      case 130: 
        return QueueStatus.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Flutter → iOS への呼び出しインターフェース
///
/// iPhoneからメッセージを送信したり、キュー状態を取得したりする
class MessageHostApi {
  /// Constructor for [MessageHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MessageHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// メッセージを送信
  ///
  /// transferUserInfoを使ってApple Watchに送信される
  /// 学習ポイント:
  /// - すべてのメッセージがキューに保持される（最新のみではない）
  /// - 送信順序が保証される
  /// - オフライン時もキューに追加され、接続回復後に配信される
  Future<void> sendMessage(MessageData message) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.MessageHostApi.sendMessage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[message]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 送信済みメッセージ一覧を取得
  Future<List<MessageData>> getSentMessages() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.MessageHostApi.getSentMessages$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MessageData>();
    }
  }

  /// 受信メッセージ一覧を取得
  Future<List<MessageData>> getReceivedMessages() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.MessageHostApi.getReceivedMessages$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MessageData>();
    }
  }

  /// キュー状態を取得
  ///
  /// outstandingUserInfoTransfersの情報を返す
  Future<QueueStatus> getQueueStatus() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.MessageHostApi.getQueueStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as QueueStatus?)!;
    }
  }

  /// 特定のメッセージの転送をキャンセル
  Future<bool> cancelMessage(String messageId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.MessageHostApi.cancelMessage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[messageId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// メッセージを既読にする
  Future<void> markAsRead(String messageId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.MessageHostApi.markAsRead$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[messageId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Watchの到達可能性をチェック
  Future<bool> isWatchReachable() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.MessageHostApi.isWatchReachable$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

/// iOS → Flutter への通知インターフェース
///
/// Apple Watchからメッセージが届いたときにFlutterに通知する
abstract class MessageFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// メッセージが受信されたことを通知
  ///
  /// Apple Watchからメッセージが届いたときに呼ばれる
  void onMessageReceived(MessageData message);

  /// キュー状態が変更されたことを通知
  void onQueueStatusChanged(QueueStatus status);

  /// 到達可能性が変更されたことを通知
  void onReachabilityChanged(bool isReachable);

  static void setUp(MessageFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onMessageReceived$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onMessageReceived was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MessageData? arg_message = (args[0] as MessageData?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onMessageReceived was null, expected non-null MessageData.');
          try {
            api.onMessageReceived(arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onQueueStatusChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onQueueStatusChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final QueueStatus? arg_status = (args[0] as QueueStatus?);
          assert(arg_status != null,
              'Argument for dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onQueueStatusChanged was null, expected non-null QueueStatus.');
          try {
            api.onQueueStatusChanged(arg_status!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onReachabilityChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onReachabilityChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_isReachable = (args[0] as bool?);
          assert(arg_isReachable != null,
              'Argument for dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onReachabilityChanged was null, expected non-null bool.');
          try {
            api.onReachabilityChanged(arg_isReachable!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
