// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class SessionInitializeResult {
  SessionInitializeResult({
    required this.success,
    required this.statusKey,
  });

  bool success;

  String statusKey;

  Object encode() {
    return <Object?>[
      success,
      statusKey,
    ];
  }

  static SessionInitializeResult decode(Object result) {
    result as List<Object?>;
    return SessionInitializeResult(
      success: result[0]! as bool,
      statusKey: result[1]! as String,
    );
  }
}

class CounterRequest {
  CounterRequest({
    required this.counter,
  });

  int counter;

  Object encode() {
    return <Object?>[
      counter,
    ];
  }

  static CounterRequest decode(Object result) {
    result as List<Object?>;
    return CounterRequest(
      counter: result[0]! as int,
    );
  }
}

class CounterResult {
  CounterResult({
    required this.success,
  });

  bool success;

  Object encode() {
    return <Object?>[
      success,
    ];
  }

  static CounterResult decode(Object result) {
    result as List<Object?>;
    return CounterResult(
      success: result[0]! as bool,
    );
  }
}

class SessionStateEvent {
  SessionStateEvent({
    required this.statusKey,
  });

  String statusKey;

  Object encode() {
    return <Object?>[
      statusKey,
    ];
  }

  static SessionStateEvent decode(Object result) {
    result as List<Object?>;
    return SessionStateEvent(
      statusKey: result[0]! as String,
    );
  }
}

class CounterUpdateEvent {
  CounterUpdateEvent({
    required this.counter,
  });

  int counter;

  Object encode() {
    return <Object?>[
      counter,
    ];
  }

  static CounterUpdateEvent decode(Object result) {
    result as List<Object?>;
    return CounterUpdateEvent(
      counter: result[0]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SessionInitializeResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is CounterRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is CounterResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is SessionStateEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CounterUpdateEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return SessionInitializeResult.decode(readValue(buffer)!);
      case 130:
        return CounterRequest.decode(readValue(buffer)!);
      case 131:
        return CounterResult.decode(readValue(buffer)!);
      case 132:
        return SessionStateEvent.decode(readValue(buffer)!);
      case 133:
        return CounterUpdateEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WatchCommunicationHostApi {
  /// Constructor for [WatchCommunicationHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WatchCommunicationHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<SessionInitializeResult> initializeSession() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.WatchCommunicationHostApi.initializeSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SessionInitializeResult?)!;
    }
  }

  Future<CounterResult> sendCounter(CounterRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_watch.WatchCommunicationHostApi.sendCounter$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as CounterResult?)!;
    }
  }
}

abstract class WatchCommunicationFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onSessionStateChanged(SessionStateEvent event);

  void onCounterUpdated(CounterUpdateEvent event);

  static void setUp(WatchCommunicationFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onSessionStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onSessionStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final SessionStateEvent? arg_event = (args[0] as SessionStateEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onSessionStateChanged was null, expected non-null SessionStateEvent.');
          try {
            api.onSessionStateChanged(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onCounterUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onCounterUpdated was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CounterUpdateEvent? arg_event = (args[0] as CounterUpdateEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.flutter_watch.WatchCommunicationFlutterApi.onCounterUpdated was null, expected non-null CounterUpdateEvent.');
          try {
            api.onCounterUpdated(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
