// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class CounterApiPigeonCodecReader: FlutterStandardReader {
}

private class CounterApiPigeonCodecWriter: FlutterStandardWriter {
}

private class CounterApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CounterApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CounterApiPigeonCodecWriter(data: data)
  }
}

class CounterApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CounterApiPigeonCodec(readerWriter: CounterApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CounterFlutterApiProtocol {
  func onCounterIncremented(count countArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onReachabilityChanged(isReachable isReachableArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class CounterFlutterApi: CounterFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CounterApiPigeonCodec {
    return CounterApiPigeonCodec.shared
  }
  func onCounterIncremented(count countArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.CounterFlutterApi.onCounterIncremented\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([countArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onReachabilityChanged(isReachable isReachableArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.CounterFlutterApi.onReachabilityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isReachableArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CounterHostApi {
  func resetCounter() throws
  func updateCounter(count: Int64) throws
  func isWatchReachable() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CounterHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CounterApiPigeonCodec.shared }
  /// Sets up an instance of `CounterHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CounterHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let resetCounterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.CounterHostApi.resetCounter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetCounterChannel.setMessageHandler { _, reply in
        do {
          try api.resetCounter()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetCounterChannel.setMessageHandler(nil)
    }
    let updateCounterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.CounterHostApi.updateCounter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateCounterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        do {
          try api.updateCounter(count: countArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateCounterChannel.setMessageHandler(nil)
    }
    let isWatchReachableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.CounterHostApi.isWatchReachable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWatchReachableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWatchReachable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWatchReachableChannel.setMessageHandler(nil)
    }
  }
}
