// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 画像メタデータ
///
/// Generated class from Pigeon that represents data sent in messages.
struct ImageMetadata {
  var id: String
  var fileName: String
  var fileSize: Int64
  var width: Int64
  var height: Int64
  var timestamp: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageMetadata? {
    let id = pigeonVar_list[0] as! String
    let fileName = pigeonVar_list[1] as! String
    let fileSize = pigeonVar_list[2] as! Int64
    let width = pigeonVar_list[3] as! Int64
    let height = pigeonVar_list[4] as! Int64
    let timestamp = pigeonVar_list[5] as! Double

    return ImageMetadata(
      id: id,
      fileName: fileName,
      fileSize: fileSize,
      width: width,
      height: height,
      timestamp: timestamp
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      fileName,
      fileSize,
      width,
      height,
      timestamp,
    ]
  }
}

/// 転送進捗情報
///
/// Generated class from Pigeon that represents data sent in messages.
struct TransferProgress {
  var imageId: String
  var progress: Double
  var bytesTransferred: Int64
  var totalBytes: Int64
  var transferSpeed: Double
  var estimatedTimeRemaining: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TransferProgress? {
    let imageId = pigeonVar_list[0] as! String
    let progress = pigeonVar_list[1] as! Double
    let bytesTransferred = pigeonVar_list[2] as! Int64
    let totalBytes = pigeonVar_list[3] as! Int64
    let transferSpeed = pigeonVar_list[4] as! Double
    let estimatedTimeRemaining = pigeonVar_list[5] as! Double

    return TransferProgress(
      imageId: imageId,
      progress: progress,
      bytesTransferred: bytesTransferred,
      totalBytes: totalBytes,
      transferSpeed: transferSpeed,
      estimatedTimeRemaining: estimatedTimeRemaining
    )
  }
  func toList() -> [Any?] {
    return [
      imageId,
      progress,
      bytesTransferred,
      totalBytes,
      transferSpeed,
      estimatedTimeRemaining,
    ]
  }
}

/// 転送履歴アイテム
///
/// Generated class from Pigeon that represents data sent in messages.
struct TransferHistoryItem {
  var metadata: ImageMetadata
  var status: Int64
  var completedAt: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TransferHistoryItem? {
    let metadata = pigeonVar_list[0] as! ImageMetadata
    let status = pigeonVar_list[1] as! Int64
    let completedAt: Double? = nilOrValue(pigeonVar_list[2])

    return TransferHistoryItem(
      metadata: metadata,
      status: status,
      completedAt: completedAt
    )
  }
  func toList() -> [Any?] {
    return [
      metadata,
      status,
      completedAt,
    ]
  }
}

private class ImageTransferApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ImageMetadata.fromList(self.readValue() as! [Any?])
    case 130:
      return TransferProgress.fromList(self.readValue() as! [Any?])
    case 131:
      return TransferHistoryItem.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ImageTransferApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ImageMetadata {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? TransferProgress {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? TransferHistoryItem {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ImageTransferApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ImageTransferApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ImageTransferApiPigeonCodecWriter(data: data)
  }
}

class ImageTransferApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ImageTransferApiPigeonCodec(readerWriter: ImageTransferApiPigeonCodecReaderWriter())
}


/// Flutter → iOS への呼び出しインターフェース
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ImageTransferHostApi {
  /// 画像を転送
  /// imageData: JPEG形式のバイナリデータ
  func transferImage(imageData: FlutterStandardTypedData, metadata: ImageMetadata, completion: @escaping (Result<Void, Error>) -> Void)
  /// 転送をキャンセル
  func cancelTransfer(imageId: String) throws
  /// 転送履歴を取得
  func getTransferHistory() throws -> [TransferHistoryItem]
  /// 進行中の転送一覧を取得
  func getActiveTransfers() throws -> [TransferProgress]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ImageTransferHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ImageTransferApiPigeonCodec.shared }
  /// Sets up an instance of `ImageTransferHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ImageTransferHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 画像を転送
    /// imageData: JPEG形式のバイナリデータ
    let transferImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.transferImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transferImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageDataArg = args[0] as! FlutterStandardTypedData
        let metadataArg = args[1] as! ImageMetadata
        api.transferImage(imageData: imageDataArg, metadata: metadataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      transferImageChannel.setMessageHandler(nil)
    }
    /// 転送をキャンセル
    let cancelTransferChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.cancelTransfer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelTransferChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imageIdArg = args[0] as! String
        do {
          try api.cancelTransfer(imageId: imageIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelTransferChannel.setMessageHandler(nil)
    }
    /// 転送履歴を取得
    let getTransferHistoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.getTransferHistory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTransferHistoryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getTransferHistory()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getTransferHistoryChannel.setMessageHandler(nil)
    }
    /// 進行中の転送一覧を取得
    let getActiveTransfersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.ImageTransferHostApi.getActiveTransfers\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getActiveTransfersChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getActiveTransfers()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getActiveTransfersChannel.setMessageHandler(nil)
    }
  }
}
/// iOS → Flutter への通知インターフェース
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ImageTransferFlutterApiProtocol {
  /// 進捗が更新された
  func onProgressUpdated(progress progressArg: TransferProgress, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 転送が完了した
  func onTransferCompleted(imageId imageIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 転送が失敗した
  func onTransferFailed(imageId imageIdArg: String, error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ImageTransferFlutterApi: ImageTransferFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ImageTransferApiPigeonCodec {
    return ImageTransferApiPigeonCodec.shared
  }
  /// 進捗が更新された
  func onProgressUpdated(progress progressArg: TransferProgress, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onProgressUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 転送が完了した
  func onTransferCompleted(imageId imageIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferCompleted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([imageIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 転送が失敗した
  func onTransferFailed(imageId imageIdArg: String, error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.ImageTransferFlutterApi.onTransferFailed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([imageIdArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
