//
//  for.swift
//  Runner
//
//  Created by Koichi Kishimoto on 2025/11/15.
//


// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// メッセージデータを表すクラス
///
/// transferUserInfoで送受信されるデータ構造
///
/// Generated class from Pigeon that represents data sent in messages.
struct MessageData {
  /// メッセージID（UUID）
  var id: String
  /// メッセージ本文
  var text: String
  /// 送信元（"iPhone" or "Watch"）
  var sender: String
  /// 送信時刻（Unix timestamp）
  var timestamp: Double
  /// 既読フラグ
  var isRead: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageData? {
    let id = pigeonVar_list[0] as! String
    let text = pigeonVar_list[1] as! String
    let sender = pigeonVar_list[2] as! String
    let timestamp = pigeonVar_list[3] as! Double
    let isRead = pigeonVar_list[4] as! Bool

    return MessageData(
      id: id,
      text: text,
      sender: sender,
      timestamp: timestamp,
      isRead: isRead
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      text,
      sender,
      timestamp,
      isRead,
    ]
  }
}

/// キュー状態を表すクラス
///
/// Generated class from Pigeon that represents data sent in messages.
struct QueueStatus {
  /// キューに残っている転送の数
  var outstandingCount: Int64
  /// 現在転送中かどうか
  var isTransferring: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> QueueStatus? {
    let outstandingCount = pigeonVar_list[0] as! Int64
    let isTransferring = pigeonVar_list[1] as! Bool

    return QueueStatus(
      outstandingCount: outstandingCount,
      isTransferring: isTransferring
    )
  }
  func toList() -> [Any?] {
    return [
      outstandingCount,
      isTransferring,
    ]
  }
}

private class MessageApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MessageData.fromList(self.readValue() as! [Any?])
    case 130:
      return QueueStatus.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessageApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MessageData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? QueueStatus {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessageApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessageApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessageApiPigeonCodecWriter(data: data)
  }
}

class MessageApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessageApiPigeonCodec(readerWriter: MessageApiPigeonCodecReaderWriter())
}

/// Flutter → iOS への呼び出しインターフェース
///
/// iPhoneからメッセージを送信したり、キュー状態を取得したりする
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MessageHostApi {
  /// メッセージを送信
  ///
  /// transferUserInfoを使ってApple Watchに送信される
  /// 学習ポイント:
  /// - すべてのメッセージがキューに保持される（最新のみではない）
  /// - 送信順序が保証される
  /// - オフライン時もキューに追加され、接続回復後に配信される
  func sendMessage(message: MessageData) throws
  /// 送信済みメッセージ一覧を取得
  func getSentMessages() throws -> [MessageData]
  /// 受信メッセージ一覧を取得
  func getReceivedMessages() throws -> [MessageData]
  /// キュー状態を取得
  ///
  /// outstandingUserInfoTransfersの情報を返す
  func getQueueStatus() throws -> QueueStatus
  /// 特定のメッセージの転送をキャンセル
  func cancelMessage(messageId: String) throws -> Bool
  /// メッセージを既読にする
  func markAsRead(messageId: String) throws
  /// Watchの到達可能性をチェック
  func isWatchReachable() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MessageHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessageApiPigeonCodec.shared }
  /// Sets up an instance of `MessageHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MessageHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// メッセージを送信
    ///
    /// transferUserInfoを使ってApple Watchに送信される
    /// 学習ポイント:
    /// - すべてのメッセージがキューに保持される（最新のみではない）
    /// - 送信順序が保証される
    /// - オフライン時もキューに追加され、接続回復後に配信される
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.MessageHostApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! MessageData
        do {
          try api.sendMessage(message: messageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    /// 送信済みメッセージ一覧を取得
    let getSentMessagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.MessageHostApi.getSentMessages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSentMessagesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSentMessages()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSentMessagesChannel.setMessageHandler(nil)
    }
    /// 受信メッセージ一覧を取得
    let getReceivedMessagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.MessageHostApi.getReceivedMessages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getReceivedMessagesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getReceivedMessages()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getReceivedMessagesChannel.setMessageHandler(nil)
    }
    /// キュー状態を取得
    ///
    /// outstandingUserInfoTransfersの情報を返す
    let getQueueStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.MessageHostApi.getQueueStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getQueueStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getQueueStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getQueueStatusChannel.setMessageHandler(nil)
    }
    /// 特定のメッセージの転送をキャンセル
    let cancelMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.MessageHostApi.cancelMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageIdArg = args[0] as! String
        do {
          let result = try api.cancelMessage(messageId: messageIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelMessageChannel.setMessageHandler(nil)
    }
    /// メッセージを既読にする
    let markAsReadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.MessageHostApi.markAsRead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      markAsReadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageIdArg = args[0] as! String
        do {
          try api.markAsRead(messageId: messageIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      markAsReadChannel.setMessageHandler(nil)
    }
    /// Watchの到達可能性をチェック
    let isWatchReachableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_watch.MessageHostApi.isWatchReachable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWatchReachableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isWatchReachable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isWatchReachableChannel.setMessageHandler(nil)
    }
  }
}
/// iOS → Flutter への通知インターフェース
///
/// Apple Watchからメッセージが届いたときにFlutterに通知する
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MessageFlutterApiProtocol {
  /// メッセージが受信されたことを通知
  ///
  /// Apple Watchからメッセージが届いたときに呼ばれる
  func onMessageReceived(message messageArg: MessageData, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// キュー状態が変更されたことを通知
  func onQueueStatusChanged(status statusArg: QueueStatus, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 到達可能性が変更されたことを通知
  func onReachabilityChanged(isReachable isReachableArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MessageFlutterApi: MessageFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessageApiPigeonCodec {
    return MessageApiPigeonCodec.shared
  }
  /// メッセージが受信されたことを通知
  ///
  /// Apple Watchからメッセージが届いたときに呼ばれる
  func onMessageReceived(message messageArg: MessageData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onMessageReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// キュー状態が変更されたことを通知
  func onQueueStatusChanged(status statusArg: QueueStatus, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onQueueStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([statusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 到達可能性が変更されたことを通知
  func onReachabilityChanged(isReachable isReachableArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_watch.MessageFlutterApi.onReachabilityChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isReachableArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
